-- Inserting data into the student table
INSERT INTO student (ID, name, dept_name) VALUES ('1', 'Aditya', 'Computer Science');
INSERT INTO student (ID, name, dept_name) VALUES ('2', 'Akanksha', 'Mathematics');
INSERT INTO student (ID, name, dept_name) VALUES ('3', 'Akshita', 'Computer Science');
INSERT INTO student (ID, name, dept_name) VALUES ('4', 'Anjali', 'Statistics');
INSERT INTO student (ID, name, dept_name) VALUES ('5', 'Devanshu', 'Mathematics');
INSERT INTO student (ID, name, dept_name) VALUES ('6', 'Divyanshu', 'Literature');
INSERT INTO student (ID, name, dept_name) VALUES ('7', 'Harshit', 'Botany');
INSERT INTO student (ID, name, dept_name) VALUES ('8', 'Jagriti', 'Computer Science');
INSERT INTO student (ID, name, dept_name) VALUES ('9', 'Tanuja', 'Mathematics');
INSERT INTO student (ID, name, dept_name) VALUES ('10', 'Stuti', 'Statistics');
INSERT INTO student (ID, name, dept_name) VALUES ('11', 'Ashish', 'Literature');
INSERT INTO student (ID, name, dept_name) VALUES ('12', 'Akash', 'Computer Science');
INSERT INTO student (ID, name, dept_name) VALUES ('13', 'Abhinav', 'Computer Science');
INSERT INTO student (ID, name, dept_name) VALUES ('14', 'Sudeepto', 'Computer Science');
INSERT INTO student (ID, name, dept_name) VALUES ('15', 'Kinshuk', 'Computer Science');
INSERT INTO student (ID, name, dept_name) VALUES ('16', 'Aviral', 'Literature');
INSERT INTO student (ID, name, dept_name) VALUES ('17', 'Apurva', 'Botany');
INSERT INTO student (ID, name, dept_name) VALUES ('18', 'Sunil', 'Statistics');
INSERT INTO student (ID, name, dept_name) VALUES ('19', 'Shubham', 'Botany');
INSERT INTO student (ID, name, dept_name) VALUES ('20', 'Vallabh', 'Mathematics');
INSERT INTO student (ID, name, dept_name) VALUES ('21', 'Gagan', 'Computer Science');
INSERT INTO student (ID, name, dept_name) VALUES ('22', 'Adarsh', 'Statistics');
INSERT INTO student (ID, name, dept_name) VALUES ('23', 'Neha', 'Statistics');
INSERT INTO student (ID, name, dept_name) VALUES ('24', 'Stuti', 'Computer Science');
INSERT INTO student (ID, name, dept_name) VALUES ('25', 'Adamya', 'Computer Science');
INSERT INTO student (ID, name, dept_name) VALUES ('26', 'Abhishek', 'Literature');
INSERT INTO student (ID, name, dept_name) VALUES ('27', 'Divya', 'Literature');
INSERT INTO student (ID, name, dept_name) VALUES ('28', 'Rohan', 'Botany');
INSERT INTO student (ID, name, dept_name) VALUES ('29', 'Rahul', 'Botany');
INSERT INTO student (ID, name, dept_name) VALUES ('30', 'Rishabh', 'Mathematics');
